CREATE TYPE type_enum as enum ('ORDINAL', 'SEASONAL');
CREATE TYPE status_enum as enum ('PENDING', 'REJECTED', 'COMPLETED');

DROP TABLE IF EXISTS ticket;
CREATE TABLE ticket
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type  varchar not null,
    price decimal not null,
    exp integer,
    zid varchar not null
);

DROP TABLE IF EXISTS orders;
CREATE TABLE orders
(
    id    bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username  bigint     not null,
    ticket_id bigint      not null,
    n_ticket  integer     not null,
    status    varchar not null
);